apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: nodejs-mybfndri
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/nodejs-mybfndri:af16f04781fa3a68195ee64e46aaefa99f429bef@sha256:05d8ae1fc4648e866f9cab1605128077106d67502658aeaa07d8a17a4f7dac12
          name: container-image
